[package]
name = "tcp_server"
version = "0.1.0"
authors = ["<bdkech@gmail.com>"]
edition = "2021"

[dependencies]
dns-parser = "0.8.0"
simplelog = "^0.7.4"
log = "0.4.8"
tokio = { version = "0.2", features = ["full"] }
